### ISSUE TITLE
DAWG Doesn't Use Envvars

### ISSUE THREAD

**Issue by corbanCloud** [mozilla/dawg#16]
Sources files and router base are being determined by checks against `window.location.host` 
Vite provides an envvar injection/import mechanism that we should use instead 

https://vitejs.dev/guide/env-and-mode.html

**Comment by whd** [comment]
The truest bestest way to fix `?useProdData=true` breaking the local dev flow is with the envvars issue here so I'm  throwing a comment to that effect on this issue.
