### ISSUE TITLE
Some links to group members are broken

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/dawg#39]
When you click on a member of a group in the Members column, some of the links come up as `https://protosaur.dev/dawg/()=>(console.log(i.value),i.value)` .

It looks like the links work fine where the member is itself another workgroup, just not for specific individuals.

A bit of digging makes me think it's the `noop` formatter [here](https://github.com/mozilla/dawg/blob/main/src/components/AutoLinker.ts#L60-L67).

**Comment by corbanCloud** [comment]
This is a one-liner fix, but I'll want to include expanding the test coverage for this component as part of the PR so that will take a little more time.

Still a small fix, should be able to fit it in this week
